services:
  atom:
    build: .
    container_name: atom
    ports:
      - "8080:80"
    depends_on:
      - db
      - elasticsearch
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: atom
      DATABASE_USER: atom
      DATABASE_PASSWORD: atom_pass
      ES_HOST: elasticsearch
    volumes:
      - ./atom:/var/www/html

  db:
    image: mariadb:10.5
    container_name: atom_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: atom
      MYSQL_USER: atom
      MYSQL_PASSWORD: atom_pass
    volumes:
      - db_data:/var/lib/mysql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.16
    container_name: atom_es
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
      - xpack.ml.enabled=false
      - xpack.watcher.enabled=false
      - xpack.graph.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data



  frontend:
    image: nginx:alpine
    container_name: atom_frontend
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./atom:/var/www/html
    depends_on:
      - atom

volumes:
  db_data:
  es_data:

